py/kalfu/kalfu/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

from kalfu.views import LoginRequiredGraphQLView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("media/", include("media.urls")),
    path("gql/", csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

py/kalfu/media/urls.py
from django.urls import path

from . import views

app_name = "media"
urlpatterns = [
    path("media/", views.MediumList.as_view(), name="list_media"),
    path("media/<str:medium_id>/delete/", views.delete_medium, name="delete_medium"),
    path(
        "media/<str:medium_id>/show/",
        views.ShowMediumView.as_view(),
        name="show_medium",
    ),
    path(
        "media/<str:medium_id>/create-tag/",
        views.CreateTaggedMediaView.as_view(),
        name="create_tagged_medium",
    ),
    path(
        "media/<str:medium_id>/update-medium-taken-at/",
        views.UpdateMediumTakenAtView.as_view(),
        name="update_medium_taken_at",
    ),
]

py/kalfu/media/models.py
import os
from datetime import timedelta
from uuid import uuid4

import boto3
import pytz
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.gis.db import models
from django.contrib.postgres.fields import HStoreField
from django.core.cache import cache
from django.utils.timezone import is_naive
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import CreationDateTimeField, ModificationDateTimeField
from taggit.managers import TaggableManager, _TaggableManager
from taggit.models import TagBase, TaggedItemBase
from timezone_field import TimeZoneField

IMAGE_FORMATS = [
    "jpeg",
    "jpg",
]
VIDEO_FORMATS = ["avi", "mp4"]


class TimeStampedModel(models.Model):
    created_at = CreationDateTimeField(_("created"))
    modified_at = ModificationDateTimeField(_("modified"))

    def save(self, **kwargs):
        self.update_modified_at = kwargs.pop(
            "update_modified_at", getattr(self, "update_modified_at", True)
        )
        super().save(**kwargs)

    class Meta:
        get_latest_by = "modified_at"
        abstract = True


class Tag(TimeStampedModel, TagBase):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    def save(self, *args, **kwargs):
        self.name = self.name.strip().lower()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")
        ordering = ["name"]


class TaggedMedium(TimeStampedModel, TaggedItemBase):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    content_object = models.ForeignKey("Medium", on_delete=models.CASCADE)
    tag = models.ForeignKey(
        Tag,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )
    confidence = models.FloatField(null=True)
    hidden_at = models.DateTimeField(null=True)
    is_machine_generated = models.BooleanField(default=False)

    @property
    def is_hidden(self):
        return self.hidden_at is not None

    class Meta:
        verbose_name = _("Tagged medium")
        verbose_name_plural = _("Tagged media")


class TaggedMediumManager(_TaggableManager):
    def visible(self):
        return self.get_queryset(
            extra_filters={f"{self.through.tag_relname()}__hidden_at": None}
        )


class Area(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ["user", "name"]


class Camera(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    point = models.PointField()
    timezone = TimeZoneField()

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ["area", "name"]


class S3Object(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    key = models.CharField(max_length=200)
    bucket_arn = models.CharField(max_length=200, default=settings.AWS_S3_BUCKET_ARN)
    size_in_bytes = models.IntegerField()

    @property
    def bucket_name(self):
        return self.bucket_arn.split(":")[-1]

    # Move the existing object to a new destination and delete the old object
    def move(self, destination_key, destination_bucket=settings.AWS_S3_BUCKET_NAME):
        source_bucket = self.bucket
        source_key = self.key
        if source_bucket == destination_bucket and source_key == destination_key:
            return

        # Copy source to destination
        s3 = boto3.resource("s3").meta.client
        s3.copy_object(
            Bucket=destination_bucket,
            Key=destination_key,
            CopySource={"Bucket": source_bucket, "Key": source_key},
        )

        # Save new identifiers
        self.bucket = destination_bucket
        self.key = destination_key
        self.save()

        # Delete the source object
        s3.delete_object(Bucket=source_bucket, Key=source_key)

    @property
    def format(self):
        return os.path.splitext(self.key.lower())[1].lstrip(".")

    def generate_presigned_url(self, expires_in=timedelta(seconds=3600)):
        key = f"{self.key}-presigned-url"
        presigned_url = cache.get(key)
        if presigned_url:
            return presigned_url
        s3 = boto3.resource("s3")
        presigned_url = s3.meta.client.generate_presigned_url(
            "get_object",
            Params={"Bucket": self.bucket, "Key": self.key},
            ExpiresIn=expires_in.total_seconds(),
        )
        cache.set(key, presigned_url, timeout=expires_in.total_seconds())
        return presigned_url

    @property
    def is_image(self):
        return self.format in IMAGE_FORMATS

    @property
    def is_video(self):
        return self.format in VIDEO_FORMATS

    class Meta:
        unique_together = ["key", "bucket_arn"]


class Medium(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    tags = TaggableManager(through=TaggedMedium, manager=TaggedMediumManager)
    machine_generated_labels_at = models.DateTimeField(null=True)
    taken_at = models.DateTimeField(null=True)
    s3_object = models.ForeignKey(S3Object, on_delete=models.PROTECT)
    point = models.PointField()

    def generate_presigned_url(self, expires_in=timedelta(seconds=86400)):
        return self.s3_object.generate_presigned_url(expires_in=expires_in)

    def set_taken_at(self, taken_at, commit=True):
        if is_naive(taken_at):
            self.taken_at = self.camera.timezone.localize(taken_at)
        else:
            self.taken_at = taken_at
        self.taken_at = self.taken_at.astimezone(pytz.timezone("UTC"))
        if commit:
            self.save()

    @property
    def is_photo(self):
        try:
            self.photo
        except Exception:
            return False
        return True

    @property
    def is_video(self):
        try:
            self.video
        except Exception:
            return False
        return True

    def has_animal(self):
        return self.tags.filter(
            name__in=["deer", "hog", "coyote", "turkey", "dog", "human"]
        ).exists()

    class Meta:
        verbose_name = _("Medium")
        verbose_name_plural = _("Media")


class Video(Medium):
    thumbnail_s3_object = models.ForeignKey(
        S3Object, on_delete=models.SET_NULL, null=True
    )
    label_detection_job_id = models.CharField(max_length=100, blank=True)
    duration = models.DurationField(null=True)


class Photo(Medium):
    exif = HStoreField(null=True)


class Settings(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    hidden_tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return f"{self.user}"

    class Meta:
        verbose_name = _("Settings")
        verbose_name_plural = _("Settings")

py/kalfu/media/forms.py
from django.core.exceptions import ValidationError
from django.forms import CharField, DateTimeField, Form, ModelForm, UUIDField
from django.forms.widgets import DateTimeInput, TextInput
from django.utils.timezone import make_naive

from .models import Medium, Tag, TaggedMedium


class UpdateMediumTakenAtForm(ModelForm):
    taken_at = DateTimeField(
        widget=DateTimeInput(
            attrs={
                "class": "form-control form-control-lg",
            }
        ),
    )

    def clean(self):
        cleaned_data = super().clean()
        cleaned_data["taken_at"] = make_naive(cleaned_data["taken_at"])
        return cleaned_data

    def save(self, commit=True):
        self.instance.set_taken_at(self.cleaned_data["taken_at"], commit=commit)

    class Meta:
        model = Medium
        fields = ["taken_at"]


class CreateTaggedMediaForm(Form):
    tags = CharField(
        max_length=200,
        widget=TextInput(
            attrs={
                "class": "form-control form-control-lg",
            }
        ),
    )
    content_object = UUIDField(
        widget=TextInput(
            attrs={"class": "form-control form-control-lg", "disabled": True}
        )
    )

    def clean_content_object(self):
        return Medium.objects.get(id=self.cleaned_data["content_object"])

    def clean_tags(self):
        tags = self.cleaned_data["tags"].split(",")
        return [Tag.objects.get_or_create(name=t.strip().lower())[0] for t in tags]

    def clean(self):
        cleaned_data = super().clean()
        for tag in cleaned_data["tags"]:
            if TaggedMedium.objects.filter(
                tag=tag, content_object=cleaned_data["content_object"]
            ).exists():
                raise ValidationError("Tagged medium already exists")
        return cleaned_data

    def save(self):
        for t in self.cleaned_data["tags"]:
            TaggedMedium.objects.create(
                tag=t, content_object=self.cleaned_data["content_object"]
            )

py/kalfu/media/views.py
import urllib

import structlog
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from .forms import CreateTaggedMediaForm, UpdateMediumTakenAtForm
from .models import Medium, TaggedMedium

logger = structlog.get_logger(__name__)


class MediumMixin:
    template_name = "media/show_medium.html"

    @property
    def medium(self):
        return Medium.objects.get(
            id=self.kwargs["medium_id"], camera__area__user=self.request.user
        )

    def get_context_data(self, **kwargs):
        medium = self.medium
        create_tagged_media_form = CreateTaggedMediaForm(
            initial={"content_object": medium.id}
        )
        update_medium_taken_at_form = UpdateMediumTakenAtForm(instance=medium)
        return {
            "area": medium.camera.area,
            "camera": medium.camera,
            "medium": medium,
            "tagged_media": TaggedMedium.objects.filter(content_object=medium).order_by(
                "tag__name"
            ),
            "create_tagged_media_form": create_tagged_media_form,
            "update_medium_taken_at_form": update_medium_taken_at_form,
        }


class ShowMediumView(MediumMixin, LoginRequiredMixin, TemplateView):
    pass


class CreateTaggedMediaView(MediumMixin, LoginRequiredMixin, FormView):
    form_class = CreateTaggedMediaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("media:show_medium", args=(self.medium.id,))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.method in ("POST", "PUT"):
            kwargs["data"] = kwargs["data"].copy()
            kwargs["data"]["content_object"] = self.medium.id
        return kwargs


class UpdateMediumTakenAtView(MediumMixin, LoginRequiredMixin, FormView):
    form_class = UpdateMediumTakenAtForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("media:show_medium", args=(self.medium.id,))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"instance": self.medium})
        return kwargs


@login_required
def delete_medium(request, medium_id):
    Medium.objects.get(id=medium_id, camera__area__user=request.user).delete()
    return redirect("media:list_media")


class MediumList(LoginRequiredMixin, ListView):
    template_name = "media/list_media.html"
    model = Medium
    paginate_by = 25

    def get_context_data(self):
        context_data = super().get_context_data()
        url_params = self.request.GET.copy()
        url_params.pop("page", None)
        context_data["url_params"] = urllib.parse.urlencode(url_params)
        return context_data

    def get_queryset(self):
        camera_id = self.request.GET.get("camera_id", None)
        media = (
            Medium.objects.all()
            .filter(camera__area__user=self.request.user)
            .order_by("-taken_at")
        )
        if camera_id:
            media = media.filter(camera__id=camera_id)
        return media


@login_required
def show_medium(request, medium_id):
    medium = Medium.objects.get(id=medium_id, camera__area__user=request.user)
    context = {
        "area": medium.camera.area,
        "camera": medium.camera,
        "medium": medium,
        "tagged_media": TaggedMedium.objects.filter(content_object=medium).order_by(
            "tag__name"
        ),
    }
    if request.method == "POST":
        data = request.POST.copy()
        data["content_object"] = medium.id
        form = CreateTaggedMediaForm(data)
        context["form"] = form
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("media:show_medium", args=(medium.id,)))
        else:
            logger.error("Form validation failed", form_errors=form.errors.as_data())
    else:
        form = CreateTaggedMediaForm(initial={"content_object": medium.id})
    context["form"] = form
    return render(request, "media/show_medium.html", context)

py/kalfu/media/templates/media/list_media.html
{% load tz %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <title>{{ object.key }}</title>
  </head>

  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">Medium</th>
                <th scope="col">Format</th>
                <th scope="col">Tags</th>
                <th scope="col">Area</th>
                <th scope="col">Taken At</th>
              </tr>
            </thead>
            <tbody>
              {% for object in object_list %}
              <tr class="{% if object.has_animal %}bg-success{% endif %}">
                <td class="w-25">
                  {% if object.is_photo %}
                  <a href="{% url 'media:show_medium' object.id %}"
                    ><img
                      src="{{object.s3_object.generate_presigned_url}}"
                      class="img-fluid img-thumbnail"
                  /></a>
                  {% else %}
                  <a href="{% url 'media:show_medium' object.id %}"
                    ><img
                      src="{{object.video.thumbnail_s3_object.generate_presigned_url}}"
                      class="img-fluid img-thumbnail"
                  /></a>
                  {% endif %}
                </td>
                <td>{{ object.s3_object.format }}</td>
                <td>{{ object.tags.all|join:", " }}</td>
                <td>{{ object.camera.area.name }}</td>
                {% timezone object.camera.timezone %}
                <td>{{ object.taken_at }}</td>
                {% endtimezone %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col">
          <nav>
            <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
              <li class="page-item">
                <a
                  class="page-link"
                  href="?page={{ page_obj.previous_page_number }}&{{ url_params }}"
                  aria-label="Previous"
                >
                  <span aria-hidden="true">&laquo;</span>
                  <span class="sr-only">Previous</span>
                </a>
              </li>
              {% endif %} {% for page in page_obj.paginator.page_range %}
              <li
                class="page-item {% if page_obj.number == page %}active{% endif %}"
              >
                <a class="page-link" href="?page={{ page }}&{{ url_params }}"
                  >{{page}}</a
                >
              </li>
              {% endfor %} {% if page_obj.has_next %}
              <li class="page-item">
                <a
                  class="page-link"
                  href="?page={{ page_obj.next_page_number }}&{{ url_params }}"
                  aria-label="Next"
                >
                  <span aria-hidden="true">&raquo;</span>
                  <span class="sr-only">Next</span>
                </a>
              </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script> -->
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

py/kalfu/media/templates/media/show_medium.html
{% load tz %} {% timezone camera.timezone %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <title>{{ medium.key }}</title>
  </head>

  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col">
          <h3>{{ medium.s3_object.key }}</h3>
          <h3>{{ area.name }}</h3>
          <h3>{{ camera.name }} - {{ camera.point }}</h3>
          <h3>{{ medium.taken_at|date:"m/d/Y G:i:s" }}</h3>
        </div>
      </div>
      <div class="row justify-content-center my-4">
        <div class="col">
          {% if medium.is_photo %}
          <img
            src="{{ medium.s3_object.generate_presigned_url }}"
            class="img-fluid"
          />
          {% else %}
          <div class="embed-responsive embed-responsive-16by9">
            <video
              width="320"
              height="240"
              poster="{{ medium.video.thumbnail_s3_object.generate_presigned_url }}"
              controls
            >
              <source
                src="{{ medium.s3_object.generate_presigned_url }}"
                type="video/mp4"
              />
            </video>
          </div>
          {% endif %}
        </div>
        <div class="col">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Confidence</th>
              </tr>
            </thead>
            <tbody>
              {% for tagged_medium in tagged_media %}
              <tr>
                <td>{{ tagged_medium.tag.name }}</td>
                <td>{{ tagged_medium.confidence|default_if_none:"-" }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      {% if medium.is_video %}
      <div class="row justify-content-center my-4">
        <div class="col">
          <img
            src="{{ medium.video.thumbnail_s3_object.generate_presigned_url }}"
            class="img-fluid"
          />
        </div>
      </div>
      {% endif %}
      <div class="row justify-content-center my-4">
        <div class="col">
          <form
            action="{% url 'media:create_tagged_medium' medium.id %}"
            method="post"
          >
            {% csrf_token %}
            <div class="form-group">
              <label for="{{ create_tagged_media_form.tags.id_for_label }}"
                >Tag</label
              >
              {{ create_tagged_media_form.tags }}
            </div>
            <button type="submit" class="btn btn-primary">Add</button>
          </form>
        </div>
        <div class="col">
          <form
            action="{% url 'media:update_medium_taken_at' medium.id %}"
            method="post"
          >
            {% csrf_token %}
            <div class="form-group">
              <label
                for="{{ update_medium_taken_at_form.taken_at.id_for_label }}"
                >Taken At</label
              >
              {{ update_medium_taken_at_form.taken_at }}
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
          </form>
        </div>
      </div>
      <div class="row justify-content-center my-4"></div>
      <div class="row justify-content-center my-4">
        <div class="col">
          <hr />
          <form
            action="{% url 'media:delete_medium' medium.id %}"
            method="post"
          >
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script> -->
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>
{% endtimezone %}